USE [master]
GO

/****** Object:  Database [FahritdinovDb]    Script Date: 14.02.2024 9:41:53 ******/
DROP DATABASE [FahritdinovDb]
GO

/****** Object:  Database [FahritdinovDb]    Script Date: 14.02.2024 9:41:53 ******/
CREATE DATABASE [FahritdinovDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FahritdinovDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FahritdinovDb.mdf' , SIZE = 13248KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'FahritdinovDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FahritdinovDb_log.ldf' , SIZE = 1536KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FahritdinovDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FahritdinovDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FahritdinovDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FahritdinovDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FahritdinovDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FahritdinovDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [FahritdinovDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FahritdinovDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FahritdinovDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FahritdinovDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FahritdinovDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FahritdinovDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FahritdinovDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FahritdinovDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FahritdinovDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FahritdinovDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FahritdinovDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FahritdinovDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FahritdinovDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FahritdinovDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FahritdinovDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FahritdinovDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FahritdinovDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FahritdinovDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FahritdinovDb] SET  MULTI_USER 
GO

ALTER DATABASE [FahritdinovDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FahritdinovDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FahritdinovDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FahritdinovDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [FahritdinovDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FahritdinovDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [FahritdinovDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FahritdinovDb] SET  READ_WRITE 
GO

